// Generated by scripts/build-legal.mjs — don't hand-edit src/data/legal.json.
import docs from "../data/legal.json";

export const LEGAL_DOCS = docs;

// Compared against Settings.accepted_legal_version.
export const LEGAL_VERSION = `${docs.terms.updated}|${docs.privacy.updated}`;
